#if __GNUC__ < 6
#	error "Please use gcc whose version >= 6"
#	error "This error is generated by laekov, author of this project"
#endif

#ifdef WIN32
#	warning "This project is not and will never be promised to run correctly under windows."
#	warning "This warning is generated by laekov, author of this project"
#endif

